name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-actions@v2

      - name: Build Docker image
        run: docker build -t stephengrider/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true stephengrider/docker-react npm run test
